### ISSUE TITLE
Прошу, для всех, запретить прямые коммиты в main и develop

### ISSUE THREAD

**Issue by iluwaaa** [iamwhoamianamy/flop.net#10]
Так же для возможности слития добавить **не только ревью**, но и [**проверку на сборку**](https://github.com/iamwhoamianamy/flop.net/actions/workflows/dotnet.yml), а в дальнейшем и прохождение юнит тестов

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by iamwhoamianamy** [comment]
Сделано
