### ISSUE TITLE
Написать вики страничку для Geometry

### ISSUE THREAD

**Issue by DashZi** [iamwhoamianamy/flop.net#107]

**Comment by Wasilkas** [comment]
1) Там где написано просто свойство, нужно описать что оно делает. 
isClosed - замкнута фигура или нет;
Points - коллекция вершин многоугольника;
BoundingBoxRotated - описывающий прямоугольник который принимает поворот фигуры;
BoundingBox - описывающий прямоугольник стороны которого параллельны осям координат;
Если что-то забыл, и возникнут вопросы пиши. 

2) В вики есть своё форматирование для кода. На примере move посмотри, я сделал. 

3) Метод move осуществляет параллельный перенос всех вершин фигуры. 

4) Метод Scale получает на вход точку-множитель, в зависимости от значения которой фигура увеличивается(>1) или уменьшается (0;1);
Там теперь ещё изменено определение этой функции, посмотри в ветке develop.

5) Добавлен новый функционал, его также нужно внести. Также см. develop в папке model файлы всё кроме Figure, DrawingParameters, Layer, TrulyObservableCollection. 

6) Словосочетание полигон точек в PolygonBuilder заменить на что-то получше, например, многоугольник или экземпляр класса Polygon. 

7) CreateTriangle по 2 точкам создаёт равнобедренный треугольник. 

8) CreateEllipse создаёт эллипс по 2 точкам, 3-ий параметр это число точек в эллипсе, по умолчанию рассчитывается автоматически.
