### ISSUE TITLE
3. 4. Перечислить команды, необходимые для работы GUI.

### ISSUE THREAD

**Issue by iamwhoamianamy** [iamwhoamianamy/flop.net#22]

**Comment by murkykiska** [comment]
Рисование:
 - CreateLine - рисование линии
 - CreatePolyLine - рисование ломанной
 - CreateEllipse
 - CreateRectangle
 
Масштабирование (об этом будет отдельный разговор, т.к. есть возможность масштабировать и элементы приложения):
 - SceneZoomIn - Приблизить
 - SceneZoomOut - Отдалить
 - SceneZoomReset - Сбросить мастабирование

Объектный режим
 - FigureMove - Перемещение
 - FigureScale - Масштабирование фигуры
 - FigureRotate - Поворот фигуры
 - FigureDelete - Удаление фигуры
 
Режим трансформации
 - TransformAddNode - Добавить вершину
 - TransformDeleteNode - Удалить вершину
 
Меню сохранения:
 - Сохранить
 - Сохранить как
 - Экспорт в PNG
 ...
 (об этом тоже пока рано говорить)

_P.S. На счет названий, выбирайте сами куда лучше в имени команды название раздела засунуть, в начало или вперед, но мне кажется, что было бы круто, если бы название содержалось._
