### ISSUE TITLE
4. 3. DrawingParameters

### ISSUE THREAD

**Issue by murkykiska** [iamwhoamianamy/flop.net#31]
1. Не согласен с вашим методом именования, все же хотелось бы знать сначала объект, а потом характеристику. Или же именовать так, чтобы названия совпадали с полями в wpf. В дальнейшем я именую так как это есть в WPF, и пишу нужные типы.
2. Требуются следующие данные:
 - Brush Fill (заливка фигуры) 
 - Brush Stroke (цвет границы)
 - int StrokeThickness (толщина границы)
 - PenLineCap PenLineCap (форма на концах штрихов)
 - List<double> StrokeDashArray (длина штрихов вместе с оступами) 
 - double Opacity (програчность)
 - int ZIndex (положение на слое, 0 - элемент ниже, 1, 2, 3.. - элемент выше)

**Comment by iamwhoamianamy** [comment]
Сделали.
