### ISSUE TITLE
Добавить текущие DrawParametrs в MainWindowVM

### ISSUE THREAD

**Issue by murkykiska** [iamwhoamianamy/flop.net#70]
Данные параметры нужны именно там, потому что для главного окна DataContext = MainWindowVM. Они же понадобятся при рисовании фигуры. Нужны следующие параметры:

- Brush CurrentFillColor
- Brush CurrentStrokeColor
- int CurrentSrokeThickness
- PenLineCap CurrentStrokeDashCap

Делать их с учетом INotifyPropertyChanged

**Comment by sergeypobwer** [comment]
Из обсуждения:
> Можно сделать паблик экземпляр класса DrawingParameters, а не реализовывать все переменные по отдельности.
