### ISSUE TITLE
Сделать команду для выбора фигуры

### ISSUE THREAD

**Issue by iamwhoamianamy** [iamwhoamianamy/flop.net#77]
Создать public свойство ActiveFigure, которое будет ссылаться на активную в данный момент фигуру.
Создать RelayCommand SetActiveFigure который будет принимать параметром точку, перебирать все фигуры активного слоя на попадание точки в фигуру с помощью метода IsIn и устанавливать найденную фигуру в ActiveFigure. Если никакая фигура не была найдена, ActiveFigure = null.

**Comment by iluwaaa** [comment]
@krtisheva, #72, какой eps использовать во всей VM?

**Comment by iluwaaa** [comment]
Может его сделать необязательным параметром?

**Comment by krtisheva** [comment]
@iluwaaa, eps - это расстояние на которое можно по фигуре промахнуться. Вообще можно выбрать его любым, но не слишком большим. Могу сделать его необязательным.

**Comment by iluwaaa** [comment]
> @iluwaaa, eps - это расстояние на которое можно по фигуре промахнуться. Вообще можно выбрать его любым, но не слишком большим. Могу сделать его необязательным.

Спасибо
