### ISSUE TITLE
Добавить проверку прохождения тестов в Action

### ISSUE THREAD

**Issue by iluwaaa** [iamwhoamianamy/flop.net#9]
В каждую ветку был добавлен функционал на проверку сборки решения, и так же загрузку артефактов.
https://github.com/iamwhoamianamy/flop.net/actions/runs/1867345141

После того как создадите свой проект, необходимо в [файл](https://github.com/iamwhoamianamy/flop.net/blob/main/.github/workflows/dotnet.yml) добавить проверку прохождения всех ваших тестов, **_отдельным рабочим процессом_**. [По инструкции](https://docs.microsoft.com/en-us/dotnet/devops/dotnet-test-github-action). 

_Но сделать, так, чтобы при непрохождении тесте, была не error, а warning_

**Comment by Parfentia** [comment]
Нецелесообразно, потому что легче тестировать руками.
